# ===================================================================
server:
  port: 8090
# gongsi properties
# ===================================================================
spring:
    datasource:
        name: mini
        url: jdbc:mysql://192.168.1.136:3306/mini?useUnicode=true&characterEncoding=UTF-8
        username: wuyu
        password: 123456a
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:com.gongsi.mini.dao.*.xml
  type-aliases-package: com.gongsi.mini.dao

# logback
logging:
  file: /home/apps/logs/mini
  enableConsole: true