package com.gongsi.mini.dao;

import com.gongsi.mini.entities.StockCode;
import com.gongsi.mini.entities.StockCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    long countByExample(StockCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    int deleteByExample(StockCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    int insert(StockCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    int insertSelective(StockCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    List<StockCode> selectByExample(StockCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    StockCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StockCode record, @Param("example") StockCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StockCode record, @Param("example") StockCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockCode record);
}